discord:
  token: ""
  owner: ""
  guild: ""
  prefix: ""
  status: "%online% kiÅŸi oynuyor!"
  verifyCommandList:
    - "give %player% diamond 20"
  channels:
    suggestions: ""
    joinleave: ""
    verify: ""
    dailyreward: ""
    discordchat: ""
    consoleMirror: ""
discordchat:
    format: "%player% > %message%"
modules:
  suggestionModule: true
  joinLeaveModule: true
  verifyModule: true
  dailyRewardModule: true
  discordChatModule: true
  sudoModule: true
  2faModule: true
  ticketModule: true
  consoleModule: true
2faPlayers:
  - "KardasLand"
2faWhitelist:
  - "/login"
changePlayerNameAfterVerify: true
remember2FAIPAddresses: true
suggestionTime: 20 # second
autosaveTime: 300 # second
sql:
  type: "sqlite"
  host: "localhost"
  database: ""
  username: ""
  password: ""
  port: 3306